//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.15 at 05:01:25 PM GMT 
//


package com.in28minutes.courses;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.in28minutes.courses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetCourseDetailsRequest_QNAME = new QName("http://in28minutes.com/courses", "GetCourseDetailsRequest");
    private final static QName _GetCourseDetailsResponse_QNAME = new QName("http://in28minutes.com/courses", "GetCourseDetailsResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.in28minutes.courses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCourseDetailsRequestType }
     * 
     */
    public GetCourseDetailsRequestType createGetCourseDetailsRequestType() {
        return new GetCourseDetailsRequestType();
    }

    /**
     * Create an instance of {@link GetCourseDetailsResponseType }
     * 
     */
    public GetCourseDetailsResponseType createGetCourseDetailsResponseType() {
        return new GetCourseDetailsResponseType();
    }

    /**
     * Create an instance of {@link CourseDetailsType }
     * 
     */
    public CourseDetailsType createCourseDetailsType() {
        return new CourseDetailsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCourseDetailsRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetCourseDetailsRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://in28minutes.com/courses", name = "GetCourseDetailsRequest")
    public JAXBElement<GetCourseDetailsRequestType> createGetCourseDetailsRequest(GetCourseDetailsRequestType value) {
        return new JAXBElement<GetCourseDetailsRequestType>(_GetCourseDetailsRequest_QNAME, GetCourseDetailsRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCourseDetailsResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetCourseDetailsResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://in28minutes.com/courses", name = "GetCourseDetailsResponse")
    public JAXBElement<GetCourseDetailsResponseType> createGetCourseDetailsResponse(GetCourseDetailsResponseType value) {
        return new JAXBElement<GetCourseDetailsResponseType>(_GetCourseDetailsResponse_QNAME, GetCourseDetailsResponseType.class, null, value);
    }

}
